### ISSUE TITLE
LWC examples should use connectedCallback

### ISSUE THREAD

**Issue by kevinv11n** [victorgz/sfdc-apex-continuations#1]
Consider the code at https://github.com/victorgz/sfdc-apex-continuations/blob/master/force-app/main/default/lwc/apexSimpleContinuationForLWC/apexSimpleContinuationForLWC.js#L9:

```js
  renderedCallback() {
    startContinuation()
    ....
```

Per https://developer.salesforce.com/docs/component-library/documentation/en/lwc/reference_lifecycle_hooks:

>If you use renderedCallback() to perform a one-time operation, you must track it manually (using an initialRender private property, for example). 

I recommend changing renderedCallback to connectedCallback instead. Or add a large comment indicating the sample code is using an anti-pattern.

https://developer.salesforce.com/blogs/2020/05/apex-continuations-implementation-and-testing-in-aura-lwc.html also needs to be updated as it contains the same snippet of code.

**Comment by victorgz** [comment]
Hi @kevinv11n, thanks for the feedback. Already fixed using the connectedCallback lifecycle hook.
